extraction:
  cpp:
    after_prepare: 
      - python report.py 24
  cobol:
    after_prepare: 
      - python report.py 24
  csharp:
    after_prepare: 
      - python report.py 24
  java:
    after_prepare: 
      - python report.py 24
  javascript:
    after_prepare: 
      - python report.py 24
  python:
    after_prepare: 
      - python report.py 24
